defaults:
  - config
  - _self_

data:
  train_ds:
    - cifar10
  val_ds:
    - cifar10
  test_ds:
    - cifar10

model:
  arch: grid_diffusion

train:
  batch_size: 512
  model_selection_metric: val/loss
  epochs: 1000
  lr: 1.953125e-06  # 1e-3 / 512
  scheduler: LinearWarmupCosineAnnealingLR

test:
  batch_size: ${train.batch_size}
  split: train

vis:
  num_instances: 51200

log:
  name: cifar10
  project: image_diffusion

resolution: 64
ndim: 2
channels: 3