defaults:
  - shapenet_v1_vae
  - _self_

files:
  points:
    train:
      - samples/uniform_random.npz
      - samples/surface_random.npz
      - samples/uniform_sphere_0.npz
      - samples/uniform_sphere_1.npz
      - samples/uniform_sphere_2.npz
      - samples/uniform_sphere_3.npz
      - samples/uniform_sphere_4.npz
      - samples/uniform_sphere_5.npz
    val:
      - samples/uniform_random.npz
      - samples/uniform_sphere_0.npz
      - samples/uniform_sphere_1.npz
      - samples/uniform_sphere_2.npz
      - samples/uniform_sphere_3.npz
      - samples/uniform_sphere_4.npz
      - samples/uniform_sphere_5.npz
    test:
      - samples/uniform_random.npz
      - samples/uniform_sphere_0.npz
      - samples/uniform_sphere_1.npz
      - samples/uniform_sphere_2.npz
      - samples/uniform_sphere_3.npz
      - samples/uniform_sphere_4.npz
      - samples/uniform_sphere_5.npz

data:
  num_files:
    train: 100
  scale: True
  frame: net

inputs:
  type:
    - pointcloud
    - depth
  type_p:
    - 0.9
    - 0.1
  load_random: True

points:
  load_all: False

train:
  lr: 3.125e-6  # 1e-4 w/ batch size 32
  warmup_frac: 0.011
  batch_size: 128
  epochs: 100
  load_surface_points: True

val:
  freq: 1

log:
  project: vae_for_ldm