#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
cd "$REPO_ROOT"

echo "==> ruff (scoped)"
uv run ruff check \
    dataset/__init__.py \
    dataset/scripts/process_dataset.py \
    dataset/scripts/__init__.py \
    dataset/src/__init__.py \
    dataset/src/bop.py \
    dataset/src/coco.py \
    dataset/src/completion3d.py \
    dataset/src/fields.py \
    dataset/src/graspnet.py \
    dataset/src/image.py \
    dataset/src/modelnet.py \
    dataset/src/shapenet.py \
    dataset/src/shared.py \
    dataset/src/tabletop.py \
    dataset/src/transforms.py \
    dataset/src/tv_transforms.py \
    dataset/src/utils.py \
    dataset/src/ycb.py \
    dataset/tests/__init__.py \
    dataset/tests/test_coco.py \
    dataset/tests/test_datasets.py \
    dataset/tests/test_fields.py \
    dataset/tests/test_graspnet.py \
    dataset/tests/test_process_dataset_script.py \
    dataset/tests/test_tabletop.py \
    dataset/tests/test_transforms.py \
    dataset/tests/test_utils.py \
    eval/__init__.py \
    eval/scripts/compare_eval.py \
    eval/scripts/eval.py \
    eval/scripts/gen_eval.py \
    eval/scripts/generate.py \
    eval/scripts/mesh_eval.py \
    eval/scripts/__init__.py \
    eval/src/__init__.py \
    eval/src/gen_metrics.py \
    eval/src/prd.py \
    eval/src/prdc.py \
    eval/src/utils.py \
    eval/tests/test_metrics.py \
    eval/tests/test_prd.py \
    eval/tests/test_prdc.py \
    eval/tests/test_public_api.py \
    eval/tests/test_scripts_smoke.py \
    eval/tests/test_utils_metrics.py \
    eval/tests/__init__.py \
    inference/__init__.py \
    inference/conf/__init__.py \
    inference/scripts/__init__.py \
    inference/scripts/inference_mesh_tutorial.py \
    inference/scripts/inference_pointcloud.py \
    inference/src/__init__.py \
    inference/src/utils.py \
    inference/tests/test_inference_pointcloud_smoke.py \
    inference/tests/test_inference_mesh_tutorial_smoke.py \
    inference/tests/__init__.py \
    inference/tests/test_public_api.py \
    inference/tests/test_utils.py \
    libs/libmanager.py \
    libs/__init__.py \
    libs/libkinect/__init__.py \
    libs/libemd/test_emd.py \
    libs/libpointnet/__init__.py \
    libs/libchamfer/__init__.py \
    libs/libemd/__init__.py \
    libs/libchamfer/setup.py \
    libs/libemd/setup.py \
    libs/libfusion/cpu/setup.py \
    libs/libfusion/gpu/setup.py \
    libs/libintersect/inside_mesh.py \
    libs/libintersect/setup.py \
    libs/libkinect/setup.py \
    libs/libmise/setup.py \
    libs/libpointnet/pointnet2_ops/__init__.py \
    libs/libpointnet/pointnet2_ops/_version.py \
    libs/libpointnet/pointnet2_ops/pointnet2_utils.py \
    libs/libpointnet/pointnet2_ops/pointnet2_modules.py \
    libs/libpointnet/setup.py \
    libs/libpvconv/functional/backend.py \
    libs/libpvconv/functional/ball_query.py \
    libs/libpvconv/functional/devoxelization.py \
    libs/libpvconv/functional/grouping.py \
    libs/libpvconv/functional/interpolatation.py \
    libs/libpvconv/functional/voxelization.py \
    libs/libpvconv/pvconv.py \
    libs/libpvconv/se.py \
    libs/libpvconv/setup.py \
    libs/libpvconv/shared_mlp.py \
    libs/libsimplify/setup.py \
    libs/libpvconv/ball_query.py \
    libs/libpvconv/functional/sampling.py \
    libs/libpvconv/voxelization.py \
    libs/vega/__init__.py \
    libs/libfusion/__init__.py \
    libs/libfusion/cpu/__init__.py \
    libs/libfusion/gpu/__init__.py \
    libs/libintersect/__init__.py \
    libs/libmise/__init__.py \
    libs/libpvconv/__init__.py \
    libs/libpvconv/functional/__init__.py \
    libs/libsimplify/__init__.py \
    libs/tests/__init__.py \
    libs/tests/test_fps.py \
    libs/tests/test_libchamfer.py \
    libs/tests/test_libfusion.py \
    libs/tests/test_libintersect.py \
    libs/tests/test_libkinect.py \
    libs/tests/test_libmise.py \
    libs/tests/test_libsimplify.py \
    models/src/autoregression/__init__.py \
    models/src/autoregression/latent.py \
    models/src/autoregression/model.py \
    models/src/autoregression/transformer.py \
    models/src/__init__.py \
    models/src/diffusion/__init__.py \
    models/src/diffusion/blocks.py \
    models/src/diffusion/model.py \
    models/src/diffusion/unet.py \
    models/src/diffusion/utils.py \
    models/src/diffusion/latent.py \
    models/src/diffusion/pvd/utils.py \
    models/src/diffusion/pvd/__init__.py \
    models/src/diffusion/pvd/modules.py \
    models/src/diffusion/pvd/pvd.py \
    models/src/diffusion/transformer.py \
    models/src/diffusion/grid.py \
    models/src/diffusion/edm.py \
    models/src/diffusion/pcd.py \
    models/src/diffusion/shape3d2vecset.py \
    models/src/dinov2.py \
    models/src/dgcnn.py \
    models/src/dpt.py \
    models/src/dvr.py \
    models/src/dmtet.py \
    models/src/fpn.py \
    models/src/conv_onet.py \
    models/src/completr.py \
    models/src/grid.py \
    models/src/hourglass.py \
    models/src/if_net.py \
    models/src/idr.py \
    models/src/mc_dropout_net.py \
    models/src/mask_rcnn.py \
    models/src/mixins.py \
    models/src/model.py \
    models/src/onet.py \
    models/src/pcn.py \
    models/src/pointnet.py \
    models/src/pointnetpp.py \
    models/src/point_transformer.py \
    models/src/pifu.py \
    models/src/pvcnn.py \
    models/src/psgn.py \
    models/src/realnvp.py \
    models/src/resnet.py \
    models/src/snowflakenet.py \
    models/src/pssnet.py \
    models/src/shape3d2vecset.py \
    models/src/shapeformer.py \
    models/src/transformer.py \
    models/src/utils.py \
    models/src/vae.py \
    models/src/vqdif.py \
    models/src/voxel.py \
    models/src/xdconf.py \
    models/tests/__init__.py \
    models/tests/test_autoregression.py \
    models/tests/test_completr.py \
    models/tests/test_conv_onet.py \
    models/tests/test_diffusion.py \
    models/tests/test_dgcnn.py \
    models/tests/test_dino.py \
    models/tests/test_dvr.py \
    models/tests/test_dpt.py \
    models/tests/test_dmtet.py \
    models/tests/test_fpn.py \
    models/tests/test_grid_diffusion.py \
    models/tests/test_grid.py \
    models/tests/test_if_net.py \
    models/tests/test_mask_rcnn.py \
    models/tests/test_misc.py \
    models/tests/test_model_base.py \
    models/tests/test_models.py \
    models/tests/test_onet.py \
    models/tests/test_pifu.py \
    models/tests/test_point_transformer.py \
    models/tests/test_pointnet.py \
    models/tests/test_pointnetpp.py \
    models/tests/test_pssnet.py \
    models/tests/test_pvcnn.py \
    models/tests/test_realnvp.py \
    models/tests/test_shape3d2vecset.py \
    models/tests/test_shapeformer.py \
    models/tests/test_tinycudann.py \
    models/tests/test_transformer.py \
    models/tests/test_utils.py \
    models/tests/test_vae.py \
    models/tests/test_vqdif.py \
    models/tests/test_xdconv.py \
    process/__init__.py \
    process/tests/__init__.py \
    process/scripts/__init__.py \
    process/scripts/add_kinect_sim.py \
    process/scripts/blender_load.py \
    process/scripts/find_uncertain_regions.py \
    process/scripts/generate_physics_poses.py \
    process/scripts/make_watertight.py \
    process/scripts/process_mesh.py \
    process/scripts/render_blenderproc.py \
    process/scripts/render_kinect.py \
    process/scripts/render_kinect_parallel.py \
    process/scripts/sdf_from_mesh.py \
    process/scripts/ycb_sfm.py \
    process/src/__init__.py \
    process/src/carve.py \
    process/src/fill.py \
    process/src/fuse.py \
    process/src/utils.py \
    process/tests/test_carve.py \
    process/tests/test_blender_load.py \
    process/tests/test_fill.py \
    process/tests/test_fuse.py \
    process/tests/test_find_pose.py \
    process/tests/test_find_uncertain_regions.py \
    process/tests/test_make_watertight.py \
    process/tests/test_process_mesh.py \
    process/tests/test_render_blenderproc.py \
    process/tests/test_render_kinect.py \
    process/tests/test_render_kinect_parallel.py \
    process/tests/test_sdf_from_mesh.py \
    process/tests/test_ycb_sfm.py \
    process/tests/test_utils.py \
    train/__init__.py \
    train/src/data_module.py \
    train/scripts/__init__.py \
    train/src/__init__.py \
    train/src/callbacks/__init__.py \
    train/src/callbacks/ema.py \
    train/src/callbacks/eval_meshes.py \
    train/src/callbacks/every_n.py \
    train/src/callbacks/generate_meshes.py \
    train/src/callbacks/test.py \
    train/src/callbacks/visualize.py \
    train/src/schedulers.py \
    train/src/utils.py \
    train/tests/test_callbacks.py \
    train/tests/test_model.py \
    train/tests/__init__.py \
    train/tests/test_data_module.py \
    train/tests/test_ema_callback.py \
    train/tests/test_eval_meshes_callback.py \
    train/tests/test_every_n.py \
    train/tests/test_generate_meshes_callback.py \
    train/tests/test_utils_helpers.py \
    train/tests/test_test_meshes_callback.py \
    train/tests/test_visualize_callback_helpers.py \
    train/tests/test_schedulers.py \
    train/tests/test_utils.py \
    train/tests/test_train_script.py \
    utils/__init__.py \
    utils/src/__init__.py \
    utils/src/logging.py \
    utils/src/runtime.py \
    utils/src/voxelizer.py \
    utils/tests/test_runtime_logging.py \
    utils/tests/__init__.py \
    utils/tests/test_utils.py \
    visualize/__init__.py \
    visualize/scripts/__init__.py \
    visualize/scripts/load_mesh.py \
    visualize/scripts/vis_inference.py \
    visualize/src/__init__.py \
    visualize/src/generator.py \
    visualize/src/visualizer.py \
    visualize/tests/test_generator.py \
    visualize/tests/test_load_mesh_script.py \
    visualize/tests/test_render_gen_script.py \
    visualize/tests/test_render_generation_process_script.py \
    visualize/tests/test_render_script.py \
    visualize/tests/test_vis_ar_quality_sweep_script.py \
    visualize/tests/test_vis_cross_attention_queries_script.py \
    visualize/tests/test_vis_data_script.py \
    visualize/tests/test_vis_latent_embedding_compare_script.py \
    visualize/tests/test_vis_latent_pca_rgb_script.py \
    visualize/tests/test_vis_inference_script.py \
    visualize/tests/test_vis_generation_process_script.py \
    visualize/tests/__init__.py \
    visualize/tests/test_renderer.py \
    visualize/tests/test_visualizer.py \
    --select E,F,B,I,RUF --ignore E501

echo "==> pyright (scoped)"
uv run pyright \
    dataset/__init__.py \
    dataset/scripts/process_dataset.py \
    dataset/scripts/__init__.py \
    dataset/src/__init__.py \
    dataset/src/bop.py \
    dataset/src/coco.py \
    dataset/src/completion3d.py \
    dataset/src/fields.py \
    dataset/src/graspnet.py \
    dataset/src/image.py \
    dataset/src/modelnet.py \
    dataset/src/shapenet.py \
    dataset/src/shared.py \
    dataset/src/tabletop.py \
    dataset/src/transforms.py \
    dataset/src/tv_transforms.py \
    dataset/src/utils.py \
    dataset/src/ycb.py \
    dataset/tests/__init__.py \
    dataset/tests/test_coco.py \
    dataset/tests/test_datasets.py \
    dataset/tests/test_fields.py \
    dataset/tests/test_graspnet.py \
    dataset/tests/test_process_dataset_script.py \
    dataset/tests/test_tabletop.py \
    dataset/tests/test_transforms.py \
    dataset/tests/test_utils.py \
    eval/__init__.py \
    eval/scripts/compare_eval.py \
    eval/scripts/eval.py \
    eval/scripts/gen_eval.py \
    eval/scripts/generate.py \
    eval/scripts/mesh_eval.py \
    eval/scripts/__init__.py \
    eval/src/__init__.py \
    eval/src/gen_metrics.py \
    eval/src/prd.py \
    eval/src/prdc.py \
    eval/src/utils.py \
    eval/tests/test_metrics.py \
    eval/tests/test_prd.py \
    eval/tests/test_prdc.py \
    eval/tests/test_public_api.py \
    eval/tests/test_scripts_smoke.py \
    eval/tests/test_utils_metrics.py \
    eval/tests/__init__.py \
    inference/__init__.py \
    inference/conf/__init__.py \
    inference/scripts/__init__.py \
    inference/scripts/inference_mesh_tutorial.py \
    inference/scripts/inference_pointcloud.py \
    inference/src/__init__.py \
    inference/src/utils.py \
    inference/tests/test_inference_pointcloud_smoke.py \
    inference/tests/test_inference_mesh_tutorial_smoke.py \
    inference/tests/__init__.py \
    inference/tests/test_public_api.py \
    inference/tests/test_utils.py \
    libs/libmanager.py \
    libs/__init__.py \
    libs/libkinect/__init__.py \
    libs/libemd/test_emd.py \
    libs/libpointnet/__init__.py \
    libs/libchamfer/__init__.py \
    libs/libemd/__init__.py \
    libs/libchamfer/setup.py \
    libs/libemd/setup.py \
    libs/libfusion/cpu/setup.py \
    libs/libfusion/gpu/setup.py \
    libs/libintersect/inside_mesh.py \
    libs/libintersect/setup.py \
    libs/libkinect/setup.py \
    libs/libmise/setup.py \
    libs/libpointnet/pointnet2_ops/__init__.py \
    libs/libpointnet/pointnet2_ops/_version.py \
    libs/libpointnet/pointnet2_ops/pointnet2_utils.py \
    libs/libpointnet/pointnet2_ops/pointnet2_modules.py \
    libs/libpointnet/setup.py \
    libs/libpvconv/functional/backend.py \
    libs/libpvconv/functional/ball_query.py \
    libs/libpvconv/functional/devoxelization.py \
    libs/libpvconv/functional/grouping.py \
    libs/libpvconv/functional/interpolatation.py \
    libs/libpvconv/functional/voxelization.py \
    libs/libpvconv/pvconv.py \
    libs/libpvconv/se.py \
    libs/libpvconv/setup.py \
    libs/libpvconv/shared_mlp.py \
    libs/libsimplify/setup.py \
    libs/libpvconv/ball_query.py \
    libs/libpvconv/functional/sampling.py \
    libs/libpvconv/voxelization.py \
    libs/vega/__init__.py \
    libs/libfusion/__init__.py \
    libs/libfusion/cpu/__init__.py \
    libs/libfusion/gpu/__init__.py \
    libs/libintersect/__init__.py \
    libs/libmise/__init__.py \
    libs/libpvconv/__init__.py \
    libs/libpvconv/functional/__init__.py \
    libs/libsimplify/__init__.py \
    libs/tests/__init__.py \
    libs/tests/test_fps.py \
    libs/tests/test_libchamfer.py \
    libs/tests/test_libfusion.py \
    libs/tests/test_libintersect.py \
    libs/tests/test_libkinect.py \
    libs/tests/test_libmise.py \
    libs/tests/test_libsimplify.py \
    models/__init__.py \
    models/src/autoregression/__init__.py \
    models/src/autoregression/latent.py \
    models/src/autoregression/model.py \
    models/src/autoregression/transformer.py \
    models/src/__init__.py \
    models/src/diffusion/__init__.py \
    models/src/diffusion/blocks.py \
    models/src/diffusion/model.py \
    models/src/diffusion/unet.py \
    models/src/diffusion/utils.py \
    models/src/diffusion/latent.py \
    models/src/diffusion/pvd/utils.py \
    models/src/diffusion/pvd/__init__.py \
    models/src/diffusion/pvd/modules.py \
    models/src/diffusion/pvd/pvd.py \
    models/src/diffusion/transformer.py \
    models/src/diffusion/grid.py \
    models/src/diffusion/edm.py \
    models/src/diffusion/pcd.py \
    models/src/diffusion/shape3d2vecset.py \
    models/src/dinov2.py \
    models/src/dgcnn.py \
    models/src/dpt.py \
    models/src/dvr.py \
    models/src/dmtet.py \
    models/src/fpn.py \
    models/src/conv_onet.py \
    models/src/completr.py \
    models/src/grid.py \
    models/src/hourglass.py \
    models/src/if_net.py \
    models/src/idr.py \
    models/src/mc_dropout_net.py \
    models/src/mask_rcnn.py \
    models/src/mixins.py \
    models/src/model.py \
    models/src/onet.py \
    models/src/pcn.py \
    models/src/pointnet.py \
    models/src/pointnetpp.py \
    models/src/point_transformer.py \
    models/src/pifu.py \
    models/src/pvcnn.py \
    models/src/psgn.py \
    models/src/realnvp.py \
    models/src/resnet.py \
    models/src/snowflakenet.py \
    models/src/pssnet.py \
    models/src/shape3d2vecset.py \
    models/src/shapeformer.py \
    models/src/transformer.py \
    models/src/utils.py \
    models/src/vae.py \
    models/src/vqdif.py \
    models/src/voxel.py \
    models/src/xdconf.py \
    models/tests/__init__.py \
    models/tests/test_autoregression.py \
    models/tests/test_completr.py \
    models/tests/test_conv_onet.py \
    models/tests/test_diffusion.py \
    models/tests/test_dgcnn.py \
    models/tests/test_dino.py \
    models/tests/test_dvr.py \
    models/tests/test_dpt.py \
    models/tests/test_dmtet.py \
    models/tests/test_fpn.py \
    models/tests/test_grid_diffusion.py \
    models/tests/test_grid.py \
    models/tests/test_if_net.py \
    models/tests/test_mask_rcnn.py \
    models/tests/test_misc.py \
    models/tests/test_model_base.py \
    models/tests/test_models.py \
    models/tests/test_onet.py \
    models/tests/test_pifu.py \
    models/tests/test_point_transformer.py \
    models/tests/test_pointnet.py \
    models/tests/test_pointnetpp.py \
    models/tests/test_pssnet.py \
    models/tests/test_pvcnn.py \
    models/tests/test_realnvp.py \
    models/tests/test_shape3d2vecset.py \
    models/tests/test_shapeformer.py \
    models/tests/test_tinycudann.py \
    models/tests/test_transformer.py \
    models/tests/test_utils.py \
    models/tests/test_vae.py \
    models/tests/test_vqdif.py \
    models/tests/test_xdconv.py \
    process/__init__.py \
    process/tests/__init__.py \
    process/scripts/__init__.py \
    process/scripts/add_kinect_sim.py \
    process/scripts/find_uncertain_regions.py \
    process/scripts/generate_physics_poses.py \
    process/scripts/make_watertight.py \
    process/scripts/process_mesh.py \
    process/scripts/render_blenderproc.py \
    process/scripts/render_kinect.py \
    process/scripts/render_kinect_parallel.py \
    process/scripts/sdf_from_mesh.py \
    process/scripts/ycb_sfm.py \
    process/src/__init__.py \
    process/src/carve.py \
    process/src/fill.py \
    process/src/fuse.py \
    process/src/utils.py \
    process/tests/test_carve.py \
    process/tests/test_blender_load.py \
    process/tests/test_fill.py \
    process/tests/test_fuse.py \
    process/tests/test_find_pose.py \
    process/tests/test_find_uncertain_regions.py \
    process/tests/test_make_watertight.py \
    process/tests/test_process_mesh.py \
    process/tests/test_render_blenderproc.py \
    process/tests/test_render_kinect.py \
    process/tests/test_render_kinect_parallel.py \
    process/tests/test_sdf_from_mesh.py \
    process/tests/test_ycb_sfm.py \
    process/tests/test_utils.py \
    train/__init__.py \
    train/src/data_module.py \
    train/scripts/__init__.py \
    train/src/__init__.py \
    train/src/callbacks/__init__.py \
    train/src/callbacks/ema.py \
    train/src/callbacks/eval_meshes.py \
    train/src/callbacks/every_n.py \
    train/src/callbacks/generate_meshes.py \
    train/src/callbacks/test.py \
    train/src/callbacks/visualize.py \
    train/src/schedulers.py \
    train/src/utils.py \
    train/tests/test_callbacks.py \
    train/tests/test_model.py \
    train/tests/__init__.py \
    train/tests/test_data_module.py \
    train/tests/test_ema_callback.py \
    train/tests/test_eval_meshes_callback.py \
    train/tests/test_every_n.py \
    train/tests/test_generate_meshes_callback.py \
    train/tests/test_utils_helpers.py \
    train/tests/test_test_meshes_callback.py \
    train/tests/test_visualize_callback_helpers.py \
    train/tests/test_schedulers.py \
    train/tests/test_utils.py \
    train/tests/test_train_script.py \
    utils/__init__.py \
    utils/src/__init__.py \
    utils/src/logging.py \
    utils/src/runtime.py \
    utils/src/voxelizer.py \
    utils/tests/test_runtime_logging.py \
    utils/tests/__init__.py \
    utils/tests/test_utils.py \
    visualize/__init__.py \
    visualize/scripts/__init__.py \
    visualize/scripts/load_mesh.py \
    visualize/scripts/vis_inference.py \
    visualize/src/__init__.py \
    visualize/src/generator.py \
    visualize/src/visualizer.py \
    visualize/tests/test_generator.py \
    visualize/tests/test_load_mesh_script.py \
    visualize/tests/test_render_gen_script.py \
    visualize/tests/test_render_generation_process_script.py \
    visualize/tests/test_render_script.py \
    visualize/tests/test_vis_ar_quality_sweep_script.py \
    visualize/tests/test_vis_cross_attention_queries_script.py \
    visualize/tests/test_vis_data_script.py \
    visualize/tests/test_vis_latent_embedding_compare_script.py \
    visualize/tests/test_vis_latent_pca_rgb_script.py \
    visualize/tests/test_vis_inference_script.py \
    visualize/tests/test_vis_generation_process_script.py \
    visualize/tests/__init__.py \
    visualize/tests/test_renderer.py \
    visualize/tests/test_visualizer.py

echo "==> pytest (CPU-safe subset)"
uv run pytest \
    dataset/tests/test_coco.py \
    dataset/tests/test_datasets.py \
    dataset/tests/test_fields.py \
    dataset/tests/test_graspnet.py \
    dataset/tests/test_process_dataset_script.py \
    dataset/tests/test_tabletop.py \
    dataset/tests/test_transforms.py \
    dataset/tests/test_utils.py \
    eval/tests/test_public_api.py \
    eval/tests/test_metrics.py \
    eval/tests/test_prd.py \
    eval/tests/test_prdc.py \
    eval/tests/test_scripts_smoke.py \
    eval/tests/test_utils_metrics.py \
    inference/tests/test_inference_pointcloud_smoke.py \
    inference/tests/test_inference_mesh_tutorial_smoke.py \
    inference/tests/test_public_api.py \
    inference/tests/test_utils.py \
    libs/tests/test_fps.py \
    libs/tests/test_libchamfer.py \
    libs/tests/test_libfusion.py \
    libs/tests/test_libintersect.py \
    libs/tests/test_libkinect.py \
    libs/tests/test_libmise.py \
    libs/tests/test_libsimplify.py \
    models/tests/test_autoregression.py \
    models/tests/test_completr.py \
    models/tests/test_conv_onet.py \
    models/tests/test_diffusion.py \
    models/tests/test_dgcnn.py \
    models/tests/test_dino.py \
    models/tests/test_dvr.py \
    models/tests/test_dpt.py \
    models/tests/test_dmtet.py \
    models/tests/test_fpn.py \
    models/tests/test_grid_diffusion.py \
    models/tests/test_grid.py \
    models/tests/test_if_net.py \
    models/tests/test_mask_rcnn.py \
    models/tests/test_misc.py \
    models/tests/test_model_base.py \
    models/tests/test_models.py \
    models/tests/test_onet.py \
    models/tests/test_pifu.py \
    models/tests/test_point_transformer.py \
    models/tests/test_pointnet.py \
    models/tests/test_pointnetpp.py \
    models/tests/test_pssnet.py \
    models/tests/test_pvcnn.py \
    models/tests/test_realnvp.py \
    models/tests/test_shape3d2vecset.py \
    models/tests/test_shapeformer.py \
    models/tests/test_tinycudann.py \
    models/tests/test_transformer.py \
    models/tests/test_utils.py \
    models/tests/test_vae.py \
    models/tests/test_vqdif.py \
    models/tests/test_xdconv.py \
    process/tests/test_carve.py \
    process/tests/test_blender_load.py \
    process/tests/test_find_pose.py \
    process/tests/test_fill.py \
    process/tests/test_fuse.py \
    process/tests/test_find_uncertain_regions.py \
    process/tests/test_make_watertight.py \
    process/tests/test_process_mesh.py \
    process/tests/test_render_blenderproc.py \
    process/tests/test_render_kinect.py \
    process/tests/test_render_kinect_parallel.py \
    process/tests/test_sdf_from_mesh.py \
    process/tests/test_ycb_sfm.py \
    process/tests/test_utils.py \
    train/tests/test_callbacks.py \
    train/tests/test_model.py \
    train/tests/test_data_module.py \
    train/tests/test_ema_callback.py \
    train/tests/test_eval_meshes_callback.py \
    train/tests/test_every_n.py \
    train/tests/test_generate_meshes_callback.py \
    train/tests/test_utils_helpers.py \
    train/tests/test_test_meshes_callback.py \
    train/tests/test_visualize_callback_helpers.py \
    train/tests/test_schedulers.py \
    train/tests/test_utils.py \
    train/tests/test_train_script.py \
    utils/tests/test_utils.py \
    utils/tests/test_runtime_logging.py \
    visualize/tests/test_generator.py \
    visualize/tests/test_load_mesh_script.py \
    visualize/tests/test_render_gen_script.py \
    visualize/tests/test_render_generation_process_script.py \
    visualize/tests/test_render_script.py \
    visualize/tests/test_vis_ar_quality_sweep_script.py \
    visualize/tests/test_vis_cross_attention_queries_script.py \
    visualize/tests/test_vis_data_script.py \
    visualize/tests/test_vis_latent_embedding_compare_script.py \
    visualize/tests/test_vis_latent_pca_rgb_script.py \
    visualize/tests/test_vis_inference_script.py \
    visualize/tests/test_vis_generation_process_script.py \
    visualize/tests/test_renderer.py \
    visualize/tests/test_visualizer.py \
    -q
